### ISSUE TITLE
Typhography loading error

### ISSUE THREAD

**Issue by yangjinhwa** [AhKi/oh-my-desk#106]
## Type
> Bug

## Description
The fonts in the manage page and widget view are not called as expected. I think there is a problem building font-face in the typhography.scss, or the bundle does not seem to be working properly.

**Comment by HyunmoAhn** [comment]
#108 Fix this issue.

from
```
src: local('나눔고딕 Regular'), url(//fonts.gstatic.com/ea/nanumgothic/v5/NanumGothic-Regular.eot);
```

to
```
src: local('나눔고딕 Regular'), url(https://fonts.gstatic.com/ea/nanumgothic/v5/NanumGothic-Regular.eot);
```

Because this is electron environment.
when do not write `https://`, Path is set `file://fonts.~~` automatically. So we don't load web font.
