### ISSUE TITLE
Tray menu custom

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#114]
## Description
Tray menu custom for usability

## Reference
[menubar](https://github.com/maxogden/menubar)

**Comment by HyunmoAhn** [comment]
https://github.com/electron/electron/issues/8396

Can make window that shape is not rectangle.

**Comment by yangjinhwa** [comment]
## View
![artboard 3 copy](https://user-images.githubusercontent.com/29908256/43896745-d1f16a46-9c14-11e8-8e4c-266695fdd2b5.png)

**Comment by HyunmoAhn** [comment]
completed released v2.0.0
