### ISSUE TITLE
Feature request: Main window view

### ISSUE THREAD

**Issue by roscoevanderboom** [AhKi/oh-my-desk#139]
I've been using the app a lot. It's good to open some apps in a new window but sometimes I want certain windows to be together like a normal browser. 

Could you add the function to create tabs in a "Main Window"?

When user "Activates" link, the app can ask if user wants to open it in the "Main Window" (maybe call it the "Desktop Window") or to open it in a new window ( widget ).

**Comment by roscoevanderboom** [comment]
Yes. 'Desktop Window' = Main browser window with tabs, like Chrome, Firefox.

**Comment by HyunmoAhn** [comment]
We will release that feature about swapping desktop version of website or mobile version of website. It will be released v2.0.0!

Features such as tabs in normal browser were discussed at the planning stage but excluded due to low need. I'll think again according to your opinion.
