### ISSUE TITLE
Overview about oh-my-desk v2.0.0

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#141]
![image](https://user-images.githubusercontent.com/23732795/46674450-1f862800-cc17-11e8-8e4c-faa6efa42172.png)

**Comment by roscoevanderboom** [comment]
wow!! new features look awesome! I really like switch mobile and desktop version feature!

**Comment by HyunmoAhn** [comment]
# Progress for release v2.0.0

## Feature
- [x] search
- [x] update
- [x] widget
- [ ] preference

## Markup
- [ ] search
- [ ] ~~update~~ 
- [ ] preference
- [ ] widget

## Detail
- [ ] Code signing

**Comment by HyunmoAhn** [comment]
completed released v2.0.0
