### ISSUE TITLE
Lose widgets after restart

### ISSUE THREAD

**Issue by roscoevanderboom** [AhKi/oh-my-desk#157]
Windows 10

After I restart computer, all new widgets were gone. Only default widget were there.

**Comment by HyunmoAhn** [comment]
Ok... I will fix it.

It may be occur because of difference "quit app" and "shut down window".

Currentlly, When quit app, Oh-My-Desk save changed information. If you want to save information, you should quit app manually, not shut down window.

I fix this first! : )

**Comment by roscoevanderboom** [comment]
At the moment, on Windows, I cannot quit app.

**Comment by HyunmoAhn** [comment]
What is your version about 'oh-my-desk'?

If you have v2.0.1, app update itself automatically.

In v2.0.2, feature updated to quit menu when right click tray icon, right bottom icon in window.

I need to update more method to quit app :)

**Comment by HyunmoAhn** [comment]
Now, When make widget or When every 5 minutes, update widget setting and preserve data if you restart window.

But It exist a limit. When update widget information(like always on top or position of widget in desktop) or delete widget, It is not updated instantly. It will update When five minutes have elapsed(Periodic save) or when quit the app normally.

If you feel that this limit is inconvenient, Please leave comment. I will spend more time fixing this.
