### ISSUE TITLE
Use site's favicon and title in Window's Taskbar

### ISSUE THREAD

**Issue by keith0305** [AhKi/oh-my-desk#169]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Window's title and icon is always oh-my-desk's default (oh my desk's logo with title "Oh_My_Desk")

**Expected behavior**
Favicon of the widget's site and <title> of the site

**URL attempting to access**
Any site

**Screenshots (Optional But May Be Requested)**
![image](https://user-images.githubusercontent.com/5112337/53796776-c6c17e00-3f6f-11e9-9e7d-7d1b5007fa7e.png)

**Oh-My-Desk Version:**
2.0.3

**OS / OS Version:**
Windows 10

**Comment by HyunmoAhn** [comment]
Sorry for late on leave a comment. ~~Why didn't mail notify me?~~

You're right. I will fix it. ~~Maybe I need some time.~~
Thank you!

**Comment by HyunmoAhn** [comment]
I will update your opinion partly.

I can change `taskbar of windowOS` title each other. It will be released after update.

But, I need to more information about convert favicon. I can get favicon of each web-site. But I don't know update `taskbar of window OS`. I tried `browserWindow.setIcon` or `browserWindow.setOverlayIcon` but It doesn't solution. 😢 

In short, I will update that change title of widget but not favicon.
Thank you for suggestion and waiting update. Need to some time to release.
 
It is screen shot that changed by url
![image](https://user-images.githubusercontent.com/23732795/56109253-adf2b200-5f8a-11e9-806e-5311c038c262.png)


I temporary close this issue. I will open when can progress about favicon.
