### ISSUE TITLE
How about add GPLv3 license boilerplate in README??

### ISSUE THREAD

**Issue by bbvch13531** [AhKi/oh-my-desk#53]
Hi oh-my-desk I'd like to suggest add GPLv3 license boilerplate in README.
Doing so, I think user can easily notice what license does oh-my-desk follow.
You can see shorter version of GPLv3 in the bottom end of [gnu.org](https://www.gnu.org/licenses/gpl-3.0.txt) also you can refer [my repo](https://github.com/bbvch13531/prefeel-lib).
Moreover, this repo looks awesome! 👍  
Have a good day.

**Comment by GeekWims** [comment]
First of all, i would like to thank you for concerning this project. 
As your suggestion, i added boilerplate in README and created a LICENSE file.
Always good luck to you!
37407e94d2efa4ff99647097778743fb622e2b09
