### ISSUE TITLE
context menu is not active.

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#57]

**Comment by HyunmoAhn** [comment]
## Reference

https://stackoverflow.com/questions/32636750/how-to-add-a-right-click-menu-in-electron-that-has-inspect-element-option-like

https://github.com/sindresorhus/electron-context-menu

**Comment by Produck** [comment]
context menu is not active. I think this is good for title of this issue

**Comment by Produck** [comment]
and i will try this issue.

**Comment by HyunmoAhn** [comment]
This issue is not working. So delete `doing` label and participant.

**Comment by HyunmoAhn** [comment]
![image](https://user-images.githubusercontent.com/23732795/42727405-017b8910-87e1-11e8-805e-c5e54ef1a6d4.png)

Add Context menu (#125)

Close this issue.
If need to add new menu, manage another issue or PR.
