### ISSUE TITLE
change logo image

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#66]

**Comment by yangjinhwa** [comment]
## View
![artboard copy](https://user-images.githubusercontent.com/29908256/43896831-1b45a464-9c15-11e8-8bdc-082172cebff4.jpg)

**Comment by HyunmoAhn** [comment]
updated in this [commit](https://github.com/AhKi/oh-my-desk/commit/81959cefcb3dabe4c1e59b34cc69870ae533242c) version 1.1.2
