### ISSUE TITLE
web widget code migration to react.

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#75]
In Current code, web widget(`src/index.html`) code is written by Pure JS.
I decide migration it. 

Migration advantages as following.

1. I didn't predict `web widget` has many content. So I start using PureJS. But Pure JS is difficult to maintenance.
2. occur duplication component(view) and logic in current react code.
3. use `scss` code in web widget but doesn't setting current environment.
4. current environment is not hot loading in develop mode.
5. When using both Pure JS and React JS, Another Person need to learn both rule and convention.
6. Unit test environment is Set about react. The other side, Pure JS test environment is not set.

**Comment by Produck** [comment]
i don't wish to be react base. As you said, We don't know how many content is in this app. It is not web site. Oh-my-desk is an app of desk. It should fast.

**Comment by HyunmoAhn** [comment]
@Produck I write 6 reason that widget code is migration from pure JS to react JS.
If you know idea about solve above 6 reason, tell me.


> It is not web site. Oh-my-desk is an app of desk. It should fast.

I don't understand your opinion.
Of course, We make app of desktop that is not a web browser. But We must make app of desktop that user can use convenient. So, I add some feature like this.
<img width="415" alt="kakaotalk_photo_2018-02-14-18-06-25" src="https://user-images.githubusercontent.com/23732795/36195980-90e18230-11b2-11e8-98c6-02711904bc2b.png">

above image is preview about new feature of web widget. 
It looks like setting view code that is written react. So I decide migration web widget code because reuse code.

And this issue is progressing [this branch](https://github.com/AhKi/oh-my-desk/tree/refactor/migration-web-widget). It is almost done.

**Comment by HyunmoAhn** [comment]
update for #77 PR
