### ISSUE TITLE
setting Application icon when build

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#88]
fix warnning about  `Application icon is not set, default Electron icon will be used`.

**Comment by yangjinhwa** [comment]
## View
![artboard 2](https://user-images.githubusercontent.com/29908256/43896811-0b8aee62-9c15-11e8-8ff3-29e4ba81ea86.png)

**Comment by HyunmoAhn** [comment]
updated in [commit](https://github.com/AhKi/oh-my-desk/commit/81959cefcb3dabe4c1e59b34cc69870ae533242c) version 1.1.2
