### ISSUE TITLE
How about add CODE_OF_CONDUCT.md to oh-my-desk?

### ISSUE THREAD

**Issue by bbvch13531** [AhKi/oh-my-desk#92]
Type of issue
 - Doc

Description
- I think opensource project should have code of conduct. 😄
How about add CODE_OF_CONDUCT.md to oh-my-desk?
If this looks good on you, could I send PR that add CODE_OF_CONDUCT.md?

**Comment by HyunmoAhn** [comment]
Thank you for suggestion our project.

I agree about your opinion. So I find reference and information. I will add `CONDE_OF_CONDUCT.md`


> If this looks good on you, could I send PR that add CODE_OF_CONDUCT.md?

I think `CODE_OF_CONDUCT.md` is important to the character of our project.
Thank you for the suggestion, but I think I'll have to work on it.

**Comment by bbvch13531** [comment]
Thank you for kind answer!
I'm glad to send informative issue to oh-my-desk.
I hope I could contribute to repo. Could I send another PR related to Doc??

**Comment by HyunmoAhn** [comment]
> Could I send another PR related to Doc??

Any content is welcome. If you send PR, I'll take a look. 
It may be rare, If the content does not agree with our opinion, it may not be reflected.

I am very pleased that you are interested.
I look forward to your continued participation.
